function base_sentences = myfunc_grab_sentences()

grandfather_passage = ["You wish to know all about my grandfather.";...
    "Well, he is nearly ninety three years old, yet he still thinks as swiftly as ever.";...
    "He dresses himself in an old black frock coat with a thick hood, usually several buttons missing.";...
    "A long beard clings to his chin, giving those who observe him a pronounced feeling of the utmost respect.";...
    "When he speaks, his voice is just a bit cracked and quivers a bit, but it pulls the listener in.";...
    "Twice each day he plays skillfully and with zest upon a small organ.";...
    "Except in the winter when the snow or ice prevents, he slowly takes a short walk in the open air each day.";...
    "We have often urged him to walk more and smoke less, but he always answers, “Banana oil!”";...
    "Grandfather likes to be modern in his language."];

rainbow_passage = ["When sunlight strikes raindrops in the air, they act like a prism and form a rainbow." ; ...
    "The rainbow is a division of white light into many beautiful colors." ; ...
    "These take the shape of a long round arch, with its path high above." ; ...
    "Its two ends apparently beyond the horizon." ; ...
    "There is, according to legend, a boiling pot of gold at one end." ; ...
    "People look, but no one ever finds it." ; ...
    "A man looks for something beyond his reach." ; ...
    "His friends say he is looking for the pot of gold at the end of the rainbow." ; ...
    "Throughout the centuries, men have explained the rainbow in various ways." ; ...
    "Some have accepted it as a miracle without physical explanation." ; ...
    "To the Hebrews, it was a token that there would be no more universal floods." ; ...
    "The Greeks used to imagine that it was a sign from the gods to foretell war or heavy rain." ; ...
    "The Norsemen considered the rainbow as a bridge." ; ...
    "The gods passed from the earth to their home in the sky." ; ...
    "Other men have tried to explain the phenomenon physically." ; ...
    "Aristotle thought that the rainbow was caused by reflection of the sun's rays by the rain." ; ...
    "Since then, physicists have found that it is not the reflection." ; ...
    "Refraction by the raindrops causes the rainbow." ; ...
    "Many complicated ideas about the rainbow have been formed." ; ...
    "The difference in the rainbow depends considerably upon the size of the water drops." ; ...
    "The width of the colored band increases as the size of the drops increases." ; ...
    "The actual primary rainbow observed is said to be the effect of superposition of a number of bows." ; ...
    "The red of the second bow falls upon the green of the first." ; ...
    "The result is to give a bow with an abnormally wide yellow band." ; ...
    "Red and green light when mixed form yellow." ; ...
    "This is a very common type of bow, one showing mainly red and yellow, with little or no green or blue."];

Caterpillar_passage = ["Do you like amusement parks?";...
    "Well I sure do.";...
    "To amuse myself, I went twice last spring.";...
    "My most memorable moment was riding on the Caterpillar, which is a gigantic roller coaster high above the ground.";...
    "When I saw how high the Caterpillar rose into the bright blue sky, I knew it was for me.";...
    "After waiting in line for thirty minutes I made it to the front.";...
    "The man measured my height to see if I was tall enough.";...
    "I gave the man my coins, asked for change, and jumped on the cart.";...
    "Tick tick tick, the Caterpillar climbed slowly up the tracks.";...
    "It went so high I could see the parking lot.";...
    "Boy was I scared.";...
    "I thought to myself there's no turning back now.";...
    "People were so scared they screamed as we swiftly zoomed fast fast and faster along the tracks.";...
    "As quickly as it started, the Caterpillar came to a stop.";...
    "Unfortunately, it was time to pack the car and drive home.";...
    "That night, I dreamt of the wild ride on the Caterpillar.";...
    "Taking a trip to the amusement park and riding on the Caterpillar was my most memorable moment ever!"];

base_sentences = [grandfather_passage; rainbow_passage; Caterpillar_passage];
end